import { annotateChart, calculateWorkspaceForwardReturns, compareTimeframes, createResearchFinding, getSelectedEvent, queryMarketConditions, type AnnotationInput, type CompareTimeframesInput, type ConditionInput, type FindingInput, type ForwardReturnsInput } from '../services/workspaceService'
import { runWithActivity } from './toolRuntime'
import { annotateChartSchema, calculateForwardReturnsSchema, compareTimeframesSchema, createResearchFindingSchema, getSelectedEventSchema, queryMarketConditionsSchema } from './schemas'

export const researchToolDefinitions: WebMCP.ModelContextTool[] = [
  { name: 'query_market_conditions', title: 'Query historical market conditions', description: 'Search the active OHLCV dataset for historical bars matching structured AND-combined quantitative conditions using only information available at or before each bar. Matching events become visible on the human chart.', inputSchema: queryMarketConditionsSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('query_market_conditions', () => queryMarketConditions(input as unknown as ConditionInput), (data) => `Found ${data.eventCount} historical events`) },
  { name: 'calculate_forward_returns', title: 'Calculate forward returns', description: 'Run a deterministic forward-return event study for current or supplied market-event IDs and update the human workspace study panel.', inputSchema: calculateForwardReturnsSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('calculate_forward_returns', () => calculateWorkspaceForwardReturns(input as unknown as ForwardReturnsInput), (data) => `Analyzed ${data.results.length} horizons across ${data.eventCount} events`) },
  { name: 'annotate_chart', title: 'Annotate chart', description: 'Create a safe plain-text annotation on a current-dataset bar or market event so the human researcher can see the agent’s context on the chart.', inputSchema: annotateChartSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('annotate_chart', () => annotateChart(input as unknown as AnnotationInput), (data) => `Added ${data.annotation.type} annotation`) },
  { name: 'create_research_finding', title: 'Create research finding', description: 'Persist a concise historical research observation in the shared workspace. Findings are observations, not trade recommendations.', inputSchema: createResearchFindingSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('create_research_finding', () => createResearchFinding(input as unknown as FindingInput), (data) => `Saved research finding “${data.finding.title}”`) },
  { name: 'get_selected_event', title: 'Get selected market event', description: 'Read the market event currently selected in the shared human workspace, including its timestamp, bar index, and matched conditions.', inputSchema: getSelectedEventSchema, annotations: { readOnlyHint: true }, execute: () => runWithActivity('get_selected_event', getSelectedEvent, (data) => `Read selected event ${data.event.id}`) },
  { name: 'compare_timeframes', title: 'Compare timeframe studies', description: 'Run the same no-lookahead condition scan and forward-return study across derived timeframes without changing the human-visible chart.', inputSchema: compareTimeframesSchema, annotations: { readOnlyHint: true }, execute: (input) => runWithActivity('compare_timeframes', () => compareTimeframes(input as unknown as CompareTimeframesInput), (data) => `Compared ${data.comparisons.length} timeframes for ${data.asset}`) },
]
