import { annotateChart, calculateWorkspaceForwardReturns, compareTimeframes, createResearchFinding, focusTrade, getSelectedEvent, optimizeWorkspaceParameters, optimizeWorkspaceUniverse, queryMarketConditions, runWorkspaceUniverseStudy, simulateWorkspaceTrades, type AnnotationInput, type CompareTimeframesInput, type ConditionInput, type FindingInput, type ForwardReturnsInput, type OptimizeParametersInput, type OptimizeUniverseInput, type SimulateTradesInput, type UniverseStudyInput } from '../services/workspaceService'
import { runWithActivity } from './toolRuntime'
import { annotateChartSchema, calculateForwardReturnsSchema, compareTimeframesSchema, createResearchFindingSchema, focusTradeSchema, getSelectedEventSchema, optimizeParametersSchema, optimizeUniverseSchema, queryMarketConditionsSchema, runUniverseStudySchema, simulateTradesSchema } from './schemas'

export const researchToolDefinitions: WebMCP.ModelContextTool[] = [
  { name: 'query_market_conditions', title: 'Query historical market conditions', description: 'Search the active OHLCV dataset for historical bars matching structured AND-combined quantitative conditions using only information available at or before each bar. Matching events become visible on the human chart.', inputSchema: queryMarketConditionsSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('query_market_conditions', () => queryMarketConditions(input as unknown as ConditionInput), (data) => `Found ${data.eventCount} historical events`) },
  { name: 'calculate_forward_returns', title: 'Calculate forward returns', description: 'Run a deterministic forward-return event study for current or supplied market-event IDs and update the human workspace study panel.', inputSchema: calculateForwardReturnsSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('calculate_forward_returns', () => calculateWorkspaceForwardReturns(input as unknown as ForwardReturnsInput), (data) => `Analyzed ${data.results.length} horizons across ${data.eventCount} events`) },
  { name: 'annotate_chart', title: 'Annotate chart', description: 'Create a safe plain-text annotation on a current-dataset bar or market event so the human researcher can see the agent’s context on the chart.', inputSchema: annotateChartSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('annotate_chart', () => annotateChart(input as unknown as AnnotationInput), (data) => `Added ${data.annotation.type} annotation`) },
  { name: 'create_research_finding', title: 'Create research finding', description: 'Persist a concise historical research observation in the shared workspace. Findings are observations, not trade recommendations.', inputSchema: createResearchFindingSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('create_research_finding', () => createResearchFinding(input as unknown as FindingInput), (data) => `Saved research finding “${data.finding.title}”`) },
  { name: 'get_selected_event', title: 'Get selected market event', description: 'Read the market event currently selected in the shared human workspace, including its timestamp, bar index, and matched conditions.', inputSchema: getSelectedEventSchema, annotations: { readOnlyHint: true }, execute: () => runWithActivity('get_selected_event', getSelectedEvent, (data) => `Read selected event ${data.event.id}`) },
  { name: 'compare_timeframes', title: 'Compare timeframe studies', description: 'Run the same no-lookahead condition scan and forward-return study across derived timeframes without changing the human-visible chart.', inputSchema: compareTimeframesSchema, annotations: { readOnlyHint: true }, execute: (input) => runWithActivity('compare_timeframes', () => compareTimeframes(input as unknown as CompareTimeframesInput), (data) => `Compared ${data.comparisons.length} timeframes for ${data.asset}`) },
  { name: 'run_universe_study', title: 'Run cross-asset universe study', description: 'Run one no-lookahead condition definition on selected or all assets at one shared timeframe and rank only adequately sampled assets using transparent chronological out-of-sample research scores. The result is visible in Universe Research.', inputSchema: runUniverseStudySchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('run_universe_study', () => runWorkspaceUniverseStudy(input as unknown as UniverseStudyInput), (data) => `Analyzed ${data.assets.length} assets at ${data.timeframe}; ${data.excludedSymbols.length} insufficient samples`) },
  { name: 'optimize_parameters', title: 'Search robust parameters', description: 'Search a bounded grid only on chronological training data, validate candidates out of sample, and favor stable neighboring parameter regions over isolated historical peaks. It does not change the active chart.', inputSchema: optimizeParametersSchema, annotations: { readOnlyHint: true }, execute: (input) => runWithActivity('optimize_parameters', () => optimizeWorkspaceParameters(input as unknown as OptimizeParametersInput), (data) => `Tested ${data.combinationsTested} ${data.symbol} configurations; ${data.candidates.length} robust candidates returned`) },
  { name: 'optimize_universe', title: 'Search universal parameter regions', description: 'Evaluate one bounded parameter space across the selected universe. Scores use median cross-asset out-of-sample quality and penalize asset failures, rather than letting one market dominate.', inputSchema: optimizeUniverseSchema, annotations: { readOnlyHint: true }, execute: (input) => runWithActivity('optimize_universe', () => optimizeWorkspaceUniverse(input as unknown as OptimizeUniverseInput), (data) => `Tested ${data.combinationsTested} shared configurations across the selected universe`) },
  { name: 'simulate_trades', title: 'Simulate historical trades', description: 'Simulate deterministic historical trades from current events using explicit entry, stop, target, maximum-hold, and OHLC collision rules. This updates the visible Trade Study; it never sends orders.', inputSchema: simulateTradesSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('simulate_trades', () => simulateWorkspaceTrades(input as unknown as SimulateTradesInput), (data) => `Simulated ${data.tradeCount} historical trades; ${data.statistics.targetHits} targets and ${data.statistics.stopHits} stops`) },
  { name: 'focus_trade', title: 'Focus historical trade', description: 'Select a simulated historical trade, focus its chart window, and show the full entry/stop/target risk-reward overlay.', inputSchema: focusTradeSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('focus_trade', () => focusTrade(String(input.tradeId ?? '')), (data) => `Focused ${data.trade.direction} ${data.trade.outcome} trade`) },
]
