import { activateAsset, focusChart, getCompactWorkspaceState, setTimeframe } from '../services/workspaceService'
import { runWithActivity } from './toolRuntime'
import { focusChartRangeSchema, getWorkspaceStateSchema, setActiveAssetSchema, setTimeframeSchema } from './schemas'

export const workspaceToolDefinitions: WebMCP.ModelContextTool[] = [
  { name: 'get_workspace_state', title: 'Get workspace state', description: 'Read a compact snapshot of the human researcher’s current QuantMCP workspace without returning the full OHLCV dataset.', inputSchema: getWorkspaceStateSchema, annotations: { readOnlyHint: true }, execute: () => runWithActivity('get_workspace_state', getCompactWorkspaceState, (data) => `Read ${data.activeAsset ?? 'empty'} workspace`) },
  { name: 'set_active_asset', title: 'Set active asset', description: 'Load an available continuous-futures asset into the shared workspace so the human chart, metrics, and subsequent tools operate on it.', inputSchema: setActiveAssetSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('set_active_asset', () => activateAsset(String(input.asset ?? '')), (data) => `Switched ${data.previousAsset ?? 'empty workspace'} to ${data.activeAsset}`) },
  { name: 'set_timeframe', title: 'Set active timeframe', description: 'Switch the shared human-agent workspace to a deterministic derived timeframe. The chart and metrics update; incompatible bar-indexed research state is cleared.', inputSchema: setTimeframeSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('set_timeframe', () => setTimeframe(String(input.timeframe ?? '')), (data) => `Changed ${data.asset} from ${data.previousTimeframe} to ${data.newTimeframe} (${data.aggregatedBarCount} bars)`) },
  { name: 'focus_chart_range', title: 'Focus chart range', description: 'Move the human-visible chart to an explicit loaded-data time range or around a current market event without reloading the dataset.', inputSchema: focusChartRangeSchema, annotations: { readOnlyHint: false }, execute: (input) => runWithActivity('focus_chart_range', () => focusChart(input as { start?: number; end?: number; eventId?: string }), (data) => data.focusedEvent ? `Focused event ${data.focusedEvent.id}` : 'Focused requested chart range') },
]
