import type { DatasetSource, SupportedTimeframe } from '../../data/types'
import type { ParameterSearchResult, UniversalParameterSearchResult, UniverseStudy } from '../../quant/universeResearch'

interface Props { sources: DatasetSource[]; selectedAssets: string[]; timeframe: SupportedTimeframe; activeAsset: string | null; study: UniverseStudy | null; parameterSearch: ParameterSearchResult | null; universalParameterSearch: UniversalParameterSearchResult | null; eventCount: number; tradeCount: number; busy: boolean; onUniverseChange: (assets: string[]) => void; onStudy: () => Promise<void>; onParameterSearch: () => Promise<void>; onUniversalSearch: () => Promise<void>; onSelectBestAsset: (symbol: string) => Promise<void> }
const fmt = (value: number) => Number.isFinite(value) ? `${(value * 100).toFixed(2)}%` : '—'

export function StrategyWorkflowPanel({ sources, selectedAssets, timeframe, activeAsset, study, parameterSearch, universalParameterSearch, eventCount, tradeCount, busy, onUniverseChange, onStudy, onParameterSearch, onUniversalSearch, onSelectBestAsset }: Props) {
  const allSelected = selectedAssets.length === sources.length
  const toggle = (symbol: string) => onUniverseChange(selectedAssets.includes(symbol) ? selectedAssets.filter((item) => item !== symbol) : [...selectedAssets, symbol])
  const universalCandidate = universalParameterSearch?.candidates[0]
  const bestParameters = parameterSearch?.candidates.find((candidate) => !candidate.rejected)
  const bestUniverseAsset = study?.assets.find((asset) => asset.rank === 1)
  const selectedBestAsset = Boolean(bestUniverseAsset?.symbol === activeAsset)
  return <section className="universe-panel panel strategy-workflow" aria-label="Strategy workflow">
    <div className="competition-flow" aria-label="Competition review workflow"><div className="flow-title"><span className="eyebrow">Strategy workflow</span><strong>Universe → evidence → review</strong></div><ol>
      <li className={selectedAssets.length ? 'complete' : ''}><b>1</b><span>Choose universe<small>{selectedAssets.length ? `${selectedAssets.length} assets selected` : 'Select markets to compare'}</small></span></li>
      <li className={universalCandidate ? 'complete' : ''}><b>2</b><span>Universal settings<small>{universalCandidate ? 'Robust shared region saved' : 'Search shared OOS parameters'}</small></span></li>
      <li className={bestUniverseAsset ? 'complete' : ''}><b>3</b><span>Pick best asset<small>{bestUniverseAsset ? `${bestUniverseAsset.symbol} ranks #1 on OOS evidence` : 'Validate the shared region'}</small></span></li>
      <li className={bestParameters ? 'complete' : ''}><b>4</b><span>Asset refinement<small>{bestParameters ? 'Optional stable region saved' : 'Optional refinement on #1 asset'}</small></span></li>
      <li className={eventCount ? 'complete' : ''}><b>5</b><span>Event study<small>{eventCount ? `${eventCount.toLocaleString()} saved-strategy signals` : 'Run on the chosen asset'}</small></span></li>
      <li className={tradeCount ? 'complete' : ''}><b>6</b><span>Trade simulation<small>{tradeCount ? `${tradeCount.toLocaleString()} trades with risk rules` : 'Declare stop, target and hold'}</small></span></li>
      <li className={tradeCount ? 'complete' : ''}><b>7</b><span>Human + agent review<small>{tradeCount ? 'Focus best and worst historical cases' : 'Unlocks after simulation'}</small></span></li>
    </ol></div>

    <div className="universe-heading workflow-step"><div><p className="eyebrow">Step 1 · Research universe</p><h2>Choose markets to compare</h2></div></div>
    <div className="universe-controls"><div><div className="panel-heading"><span>Universe</span><button className="mini-choice" onClick={() => onUniverseChange(allSelected ? [] : sources.map((source) => source.symbol))}>{allSelected ? 'Clear' : 'All assets'}</button></div><div className="asset-checks">{sources.map((source) => <label key={source.symbol}><input type="checkbox" checked={selectedAssets.includes(source.symbol)} onChange={() => toggle(source.symbol)} />{source.symbol}</label>)}</div><small>{selectedAssets.length} selected for universal validation</small></div><div className="study-definition"><span>Feasible base family</span><strong>Price &lt; SMA · RSI below threshold · Volatility percentile above threshold</strong><small>The search selects periods and thresholds; it does not reuse the old fixed SMA(200), RSI(14) &lt; 35, volatility &gt; 80 rule.</small></div></div>

    <div className="parameter-lab workflow-step"><div><p className="eyebrow">Step 2 · Universal parameter search</p><h2>Find shared robust settings</h2><p>Search the selected universe first. This saves one feasible, cross-asset region using chronological out-of-sample evidence before asset-specific research begins.</p></div><div className="lab-actions"><button className="primary-button" disabled={busy || !selectedAssets.length} onClick={() => void onUniversalSearch()}>Find universal settings</button><small>{selectedAssets.length} assets · {timeframe} · chronological OOS validation</small></div></div>
    {universalParameterSearch && <div className="parameter-result universal-result"><div><strong>Saved universal region · {universalParameterSearch.timeframe}</strong><span>{universalParameterSearch.combinationsTested} combinations · common coverage {new Date(universalParameterSearch.commonRange.start).toLocaleDateString()} – {new Date(universalParameterSearch.commonRange.end).toLocaleDateString()}</span></div>{universalParameterSearch.candidates.slice(0, 3).map((candidate, index) => <div className="parameter-candidate" key={`${index}-${JSON.stringify(candidate.parameters)}`}><b>#{index + 1}</b><code>{Object.entries(candidate.parameters).map(([key, value]) => `${key} ${value}`).join(' · ')}</code><span>cross-asset {candidate.crossAssetScore.toFixed(0)} · {candidate.perAsset.filter((item) => !item.rejected).length}/{candidate.perAsset.length} valid OOS samples</span></div>)}</div>}

    <div className="universe-heading workflow-step"><div><p className="eyebrow">Step 3 · Validate and select</p><h2>Rank assets using the saved universal region</h2></div><button className="text-button enabled" disabled={busy || !universalCandidate || !selectedAssets.length} onClick={() => void onStudy()}>Validate universal region</button></div>
    {study ? <div className="universe-results"><div className="panel-heading"><span>Out-of-sample robustness ranking</span><span>Common coverage · {new Date(study.commonRange.start).toLocaleDateString()} – {new Date(study.commonRange.end).toLocaleDateString()}</span></div><div className="universe-table" role="table"><div className="universe-row header" role="row"><span>Rank</span><span>Asset</span><span>Score</span><span>Events</span><span>OOS median</span><span>Why</span></div>{study.assets.map((asset) => <div className="universe-row" role="row" key={asset.symbol}><span>{asset.rank ? `#${asset.rank}` : '—'}</span><strong>{asset.symbol}</strong><span>{asset.researchScore ? asset.researchScore.toFixed(0) : 'Insufficient'}</span><span>{asset.outOfSampleMetrics.usableSampleCount}</span><span>{fmt(asset.outOfSampleMetrics.median)}</span><small>{asset.strengths[0] ?? asset.weaknesses[0] ?? 'No usable test sample'}</small></div>)}</div>{study.excludedSymbols.length > 0 && <p className="research-warning">Not ranked: {study.excludedSymbols.join(', ')} did not meet the minimum out-of-sample event rule.</p>}</div> : <p className="universe-empty">First save universal settings, then validate that exact region across the chosen universe. The ranking identifies the one asset that should enter focused research.</p>}
    {bestUniverseAsset && <div className="best-asset-callout"><div><span>Selected by universal validation</span><strong>#{bestUniverseAsset.rank} · {bestUniverseAsset.symbol}</strong><small>Use this asset as the shared strategy’s focused research context.</small></div><button className="primary-button" disabled={busy || selectedBestAsset} onClick={() => void onSelectBestAsset(bestUniverseAsset.symbol)}>{selectedBestAsset ? `${bestUniverseAsset.symbol} selected` : `Use ${bestUniverseAsset.symbol} for research`}</button></div>}

    <div className="parameter-lab workflow-step asset-refinement"><div><p className="eyebrow">Step 4 · Optional asset refinement</p><h2>Refine the selected best asset</h2><p>After the universal region identifies an asset, you can test a specialized variant. Event Study uses the saved refined region when available; otherwise it keeps the saved universal region.</p></div><div className="lab-actions"><button className="secondary-button" disabled={busy || !selectedBestAsset} onClick={() => void onParameterSearch()}>Refine {activeAsset ?? 'asset'} parameters</button><small>{selectedBestAsset ? 'Best asset selected · refinement available' : 'Select the #1 ranked asset first'}</small></div></div>
    {parameterSearch && <div className="parameter-result"><div><strong>Saved refined region · {parameterSearch.symbol} {parameterSearch.timeframe}</strong><span>{parameterSearch.combinationsTested} combinations · train through {new Date(parameterSearch.split.trainRange.end).toLocaleDateString()}</span></div>{parameterSearch.candidates.slice(0, 3).map((candidate, index) => <div className="parameter-candidate" key={`${index}-${JSON.stringify(candidate.parameters)}`}><b>#{index + 1}</b><code>{Object.entries(candidate.parameters).map(([key, value]) => `${key} ${value}`).join(' · ')}</code><span>OOS {candidate.test.score.toFixed(0)} · robustness {candidate.robustness.toFixed(0)} · {candidate.stability}</span></div>)}</div>}
    <p className="execution-required"><b>Steps 5–7:</b> run Event Study with the saved strategy, then Trade Simulation with explicit stop, target, holding time, entry and collision rules; only then review focused historical trades with the human and agent.</p>
  </section>
}
