import { useState } from 'react'
import type { HistoricalTrade, TradeDirection, TradeStudyStatistics } from '../../quant/tradeSimulator'

interface Props { eventCount: number; trades: HistoricalTrade[]; statistics: TradeStudyStatistics | null; selectedTradeId: string | null; disabled: boolean; onRun: (input: { direction: TradeDirection; stopMultiplier: number; targetMultiple: number; maxHoldingBars: number }) => Promise<void>; onSelect: (tradeId: string) => void }
const decimal = (value: number) => Number.isFinite(value) ? value.toFixed(2) : '—'
const percentage = (value: number) => Number.isFinite(value) ? `${(value * 100).toFixed(1)}%` : '—'
const price = (value: number) => Number.isFinite(value) ? value.toFixed(4) : '—'

export function TradeStudyPanel({ eventCount, trades, statistics, selectedTradeId, disabled, onRun, onSelect }: Props) {
  const [direction, setDirection] = useState<TradeDirection>('long'); const [stopMultiplier, setStopMultiplier] = useState(1); const [targetMultiple, setTargetMultiple] = useState(2); const [maxHoldingBars, setMaxHoldingBars] = useState(20); const selected = trades.find((trade) => trade.id === selectedTradeId) ?? null
  return <section className="trade-study panel" aria-label="Historical Trade Study">
    <div className="trade-heading"><div><p className="eyebrow">Historical research only</p><h2>Trade Study</h2></div><button className="text-button enabled" disabled={disabled || !eventCount} onClick={() => void onRun({ direction, stopMultiplier, targetMultiple, maxHoldingBars })}>Run trade study</button></div>
    <div className="trade-config"><div><span>Direction</span><div className="trade-toggle"><button className={direction === 'long' ? 'active long' : ''} onClick={() => setDirection('long')} aria-pressed={direction === 'long'}>Long</button><button className={direction === 'short' ? 'active short' : ''} onClick={() => setDirection('short')} aria-pressed={direction === 'short'}>Short</button></div></div><div><span>Entry</span><strong>Next bar open</strong></div><label><span>Stop · ATR(14)</span><input aria-label="ATR stop multiplier" type="number" min="0.1" step="0.1" value={stopMultiplier} onChange={(event) => setStopMultiplier(Number(event.target.value))} /></label><label><span>Target · R</span><input aria-label="R target multiple" type="number" min="0.1" step="0.1" value={targetMultiple} onChange={(event) => setTargetMultiple(Number(event.target.value))} /></label><label><span>Max hold · bars</span><input aria-label="Maximum holding bars" type="number" min="1" step="1" value={maxHoldingBars} onChange={(event) => setMaxHoldingBars(Number(event.target.value))} /></label></div>
    {!statistics ? <p className="trade-empty">Use the current condition events to create deterministic historical trades. Signals are entered only on the next bar open; same-bar stop/target collisions use the conservative stop-first policy.</p> : <><div className="trade-stat-grid"><div><span>Trades</span><strong>{statistics.totalTrades}</strong></div><div><span>Target hit</span><strong>{statistics.targetHits}</strong></div><div><span>Stop hit</span><strong>{statistics.stopHits}</strong></div><div><span>Timeout</span><strong>{statistics.timeouts}</strong></div><div><span>Win rate</span><strong>{percentage(statistics.winRate)}</strong></div><div><span>Avg R</span><strong>{decimal(statistics.averageR)}R</strong></div><div><span>Median R</span><strong>{decimal(statistics.medianR)}R</strong></div><div><span>Max losses</span><strong>{statistics.maxConsecutiveLosses}</strong></div></div>{statistics.ambiguous > 0 && <p className="trade-warning">{statistics.ambiguous} ambiguous OHLC collisions are excluded from aggregate outcomes.</p>}
      {selected && <div className="selected-trade"><div className="panel-heading"><span>Selected trade</span><span className={`outcome ${selected.outcome}`}>{selected.outcome.replaceAll('_', ' ')}</span></div><div className="selected-trade-grid"><span>{selected.direction}</span><span>Entry <b>{price(selected.entryPrice)}</b></span><span>Stop <b>{price(selected.stopPrice)}</b></span><span>Target <b>{price(selected.targetPrice)}</b></span><span>R:R <b>{decimal(selected.riskRewardRatio)}</b></span><span>Result <b>{decimal(selected.realizedR)}R</b></span><span>Bars <b>{selected.barsHeld}</b></span></div></div>}
      <div className="trade-list-wrap"><div className="panel-heading"><span>Simulated trades</span><span>{trades.length} total</span></div><div className="trade-list" role="table"><div className="trade-row trade-row-header" role="row"><span>#</span><span>Time</span><span>Dir</span><span>Entry</span><span>Stop</span><span>Target</span><span>RR</span><span>Outcome</span><span>R</span><span>Bars</span></div>{trades.map((trade, index) => <button className={trade.id === selectedTradeId ? 'trade-row selected' : 'trade-row'} role="row" key={trade.id} onClick={() => onSelect(trade.id)}><span>{index + 1}</span><span>{new Date(trade.entryTimestamp).toLocaleDateString()}</span><span>{trade.direction === 'long' ? 'L' : 'S'}</span><span>{price(trade.entryPrice)}</span><span>{price(trade.stopPrice)}</span><span>{price(trade.targetPrice)}</span><span>{decimal(trade.riskRewardRatio)}</span><span className={`outcome ${trade.outcome}`}>{trade.outcome.replaceAll('_', ' ')}</span><span>{decimal(trade.realizedR)}</span><span>{trade.barsHeld}</span></button>)}</div></div></>}
  </section>
}
