import { useState } from 'react'
import type { DatasetSource, SupportedTimeframe } from '../../data/types'
import type { MarketCondition } from '../../quant/marketScanner'
import type { ParameterSearchResult, UniverseStudy } from '../../quant/universeResearch'

interface Props { sources: DatasetSource[]; selectedAssets: string[]; timeframe: SupportedTimeframe; activeAsset: string | null; study: UniverseStudy | null; parameterSearch: ParameterSearchResult | null; busy: boolean; onUniverseChange: (assets: string[]) => void; onStudy: () => Promise<void>; onParameterSearch: () => Promise<void>; onUniversalSearch: () => Promise<void> }
const fmt = (value: number) => Number.isFinite(value) ? `${(value * 100).toFixed(2)}%` : '—'

export const defaultUniverseConditions: MarketCondition[] = [
  { kind: 'sma', period: 200, comparator: 'above' }, { kind: 'rsi', period: 14, comparator: 'below', threshold: 35 }, { kind: 'volatility-percentile', period: 14, lookback: 100, comparator: 'above', threshold: 80 },
]

export function UniverseResearchPanel({ sources, selectedAssets, timeframe, activeAsset, study, parameterSearch, busy, onUniverseChange, onStudy, onParameterSearch, onUniversalSearch }: Props) {
  const [mode, setMode] = useState<'asset' | 'universal'>('asset')
  const allSelected = selectedAssets.length === sources.length
  const toggle = (symbol: string) => onUniverseChange(selectedAssets.includes(symbol) ? selectedAssets.filter((item) => item !== symbol) : [...selectedAssets, symbol])
  return <section className="universe-panel panel" aria-label="Universe Research and Parameter Lab">
    <div className="universe-heading"><div><p className="eyebrow">Cross-asset validation</p><h2>Universe Research</h2></div><button className="text-button enabled" disabled={busy || !selectedAssets.length} onClick={() => void onStudy()}>Run shared study</button></div>
    <div className="universe-controls"><div><div className="panel-heading"><span>Universe</span><button className="mini-choice" onClick={() => onUniverseChange(allSelected ? [] : sources.map((source) => source.symbol))}>{allSelected ? 'Clear' : 'All assets'}</button></div><div className="asset-checks">{sources.map((source) => <label key={source.symbol}><input type="checkbox" checked={selectedAssets.includes(source.symbol)} onChange={() => toggle(source.symbol)} />{source.symbol}</label>)}</div><small>Shared with agent tools · {selectedAssets.length} selected</small></div><div className="study-definition"><span>Same condition</span><strong>Price &gt; SMA(200) · RSI(14) &lt; 35 · Vol pct &gt; 80</strong><small>{timeframe} only · 10-bar horizon · 70/30 chronological validation · min 30 events</small></div></div>
    {study ? <div className="universe-results"><div className="panel-heading"><span>Out-of-sample robustness ranking</span><span>Common coverage · {new Date(study.commonRange.start).toLocaleDateString()} – {new Date(study.commonRange.end).toLocaleDateString()}</span></div><div className="universe-table" role="table"><div className="universe-row header" role="row"><span>Rank</span><span>Asset</span><span>Score</span><span>Events</span><span>OOS median</span><span>Why</span></div>{study.assets.map((asset) => <div className="universe-row" role="row" key={asset.symbol}><span>{asset.rank ? `#${asset.rank}` : '—'}</span><strong>{asset.symbol}</strong><span>{asset.researchScore ? asset.researchScore.toFixed(0) : 'Insufficient'}</span><span>{asset.outOfSampleMetrics.usableSampleCount}</span><span>{fmt(asset.outOfSampleMetrics.median)}</span><small>{asset.strengths[0] ?? asset.weaknesses[0] ?? 'No usable test sample'}</small></div>)}</div>{study.excludedSymbols.length > 0 && <p className="research-warning">Not ranked: {study.excludedSymbols.join(', ')} did not meet the minimum out-of-sample event rule.</p>}</div> : <p className="universe-empty">Run one identical, causal study across a selected universe. Rankings prioritize out-of-sample evidence and sample confidence—not the largest historical return.</p>}
    <div className="parameter-lab"><div><p className="eyebrow">Bounded causal grid</p><h2>Parameter Lab</h2><p>Search RSI, SMA, and volatility settings on training history, then validate untouched future bars. Neighboring values must corroborate a candidate.</p></div><div className="lab-actions"><div className="mode-toggle"><button className={mode === 'asset' ? 'active' : ''} onClick={() => setMode('asset')}>Asset-specific</button><button className={mode === 'universal' ? 'active' : ''} onClick={() => setMode('universal')}>Universal</button></div><button className="primary-button" disabled={busy || (!activeAsset && mode === 'asset') || !selectedAssets.length} onClick={() => void (mode === 'asset' ? onParameterSearch() : onUniversalSearch())}>Run robust search</button><small>{mode === 'asset' ? `${activeAsset ?? 'No active asset'} · independently optimized` : `${selectedAssets.length} assets · median cross-asset score`}</small></div></div>
    {parameterSearch && <div className="parameter-result"><div><strong>Top robust region · {parameterSearch.symbol} {parameterSearch.timeframe}</strong><span>{parameterSearch.combinationsTested} combinations · train through {new Date(parameterSearch.split.trainRange.end).toLocaleDateString()}</span></div>{parameterSearch.candidates.slice(0, 3).map((candidate, index) => <div className="parameter-candidate" key={`${index}-${JSON.stringify(candidate.parameters)}`}><b>#{index + 1}</b><code>{Object.entries(candidate.parameters).map(([key, value]) => `${key} ${value}`).join(' · ')}</code><span>OOS {candidate.test.score.toFixed(0)} · robustness {candidate.robustness.toFixed(0)} · {candidate.stability}</span></div>)}</div>}
  </section>
}
