import { useState } from 'react'
import type { DatasetSource, SupportedTimeframe } from '../../data/types'
import type { MarketCondition } from '../../quant/marketScanner'
import type { ParameterSearchResult, UniversalParameterSearchResult, UniverseStudy } from '../../quant/universeResearch'

interface Props { sources: DatasetSource[]; selectedAssets: string[]; timeframe: SupportedTimeframe; activeAsset: string | null; study: UniverseStudy | null; parameterSearch: ParameterSearchResult | null; universalParameterSearch: UniversalParameterSearchResult | null; eventCount: number; tradeCount: number; busy: boolean; onUniverseChange: (assets: string[]) => void; onStudy: () => Promise<void>; onParameterSearch: () => Promise<void>; onUniversalSearch: () => Promise<void> }
const fmt = (value: number) => Number.isFinite(value) ? `${(value * 100).toFixed(2)}%` : '—'

export const defaultUniverseConditions: MarketCondition[] = [
  { kind: 'sma', period: 100, comparator: 'below' }, { kind: 'rsi', period: 11, comparator: 'below', threshold: 45 }, { kind: 'volatility-percentile', period: 14, lookback: 100, comparator: 'above', threshold: 60 },
]

export function UniverseResearchPanel({ sources, selectedAssets, timeframe, activeAsset, study, parameterSearch, universalParameterSearch, eventCount, tradeCount, busy, onUniverseChange, onStudy, onParameterSearch, onUniversalSearch }: Props) {
  const [mode, setMode] = useState<'asset' | 'universal'>('asset')
  const allSelected = selectedAssets.length === sources.length
  const toggle = (symbol: string) => onUniverseChange(selectedAssets.includes(symbol) ? selectedAssets.filter((item) => item !== symbol) : [...selectedAssets, symbol])
  const bestParameters = parameterSearch?.candidates.find((candidate) => !candidate.rejected)
  return <section className="universe-panel panel" aria-label="Universe Research and Parameter Lab">
    <div className="competition-flow" aria-label="Competition review checklist"><div className="flow-title"><span className="eyebrow">Saved strategy workflow</span><strong>Build → test → review</strong></div><ol><li className={parameterSearch || universalParameterSearch ? 'complete' : ''}><b>1</b><span>Robust settings<small>{parameterSearch ? `${bestParameters ? 'Stable region saved' : 'No valid region'} · OOS + neighbors` : universalParameterSearch ? 'Cross-asset region saved' : 'Set the strategy before testing'}</small></span></li><li className={eventCount ? 'complete' : ''}><b>2</b><span>Event study<small>{eventCount ? `${eventCount.toLocaleString()} signals use the saved strategy` : 'Generate events from those settings'}</small></span></li><li className={tradeCount ? 'complete' : ''}><b>3</b><span>Trade simulation<small>{tradeCount ? `${tradeCount.toLocaleString()} trades with stop/target` : 'Test the same strategy execution'}</small></span></li><li className={tradeCount ? 'complete' : ''}><b>4</b><span>Human + agent review<small>{tradeCount ? 'Ready for focused trade review' : 'Unlocked after simulation'}</small></span></li></ol></div>
    <div className="parameter-lab strategy-setup"><div><p className="eyebrow">Step 1 · Strategy definition</p><h2>Parameter Lab</h2><p>Start here. The search explores less restrictive, market-feasible RSI, trend, and volatility regions, then saves only robust out-of-sample candidates for later steps.</p></div><div className="lab-actions"><div className="mode-toggle"><button className={mode === 'asset' ? 'active' : ''} onClick={() => setMode('asset')}>Asset-specific</button><button className={mode === 'universal' ? 'active' : ''} onClick={() => setMode('universal')}>Universal</button></div><button className="primary-button" disabled={busy || (!activeAsset && mode === 'asset') || !selectedAssets.length} onClick={() => void (mode === 'asset' ? onParameterSearch() : onUniversalSearch())}>Find robust settings</button><small>{mode === 'asset' ? `${activeAsset ?? 'No active asset'} · saved for this strategy` : `${selectedAssets.length} assets · saved shared region`}</small></div></div>
    <div className="universe-heading"><div><p className="eyebrow">Cross-asset validation</p><h2>Universe Research</h2></div><button className="text-button enabled" disabled={busy || !selectedAssets.length} onClick={() => void onStudy()}>Run shared study</button></div>
    <div className="universe-controls"><div><div className="panel-heading"><span>Universe</span><button className="mini-choice" onClick={() => onUniverseChange(allSelected ? [] : sources.map((source) => source.symbol))}>{allSelected ? 'Clear' : 'All assets'}</button></div><div className="asset-checks">{sources.map((source) => <label key={source.symbol}><input type="checkbox" checked={selectedAssets.includes(source.symbol)} onChange={() => toggle(source.symbol)} />{source.symbol}</label>)}</div><small>Optional cross-asset validation · {selectedAssets.length} selected</small></div><div className="study-definition"><span>Feasible starting region</span><strong>Price &lt; SMA(100) · RSI(11) &lt; 45 · Vol pct &gt; 60</strong><small>{timeframe} only · 10-bar horizon · 70/30 chronological validation · min 20 events</small></div></div>
    {study ? <div className="universe-results"><div className="panel-heading"><span>Out-of-sample robustness ranking</span><span>Common coverage · {new Date(study.commonRange.start).toLocaleDateString()} – {new Date(study.commonRange.end).toLocaleDateString()}</span></div><div className="universe-table" role="table"><div className="universe-row header" role="row"><span>Rank</span><span>Asset</span><span>Score</span><span>Events</span><span>OOS median</span><span>Why</span></div>{study.assets.map((asset) => <div className="universe-row" role="row" key={asset.symbol}><span>{asset.rank ? `#${asset.rank}` : '—'}</span><strong>{asset.symbol}</strong><span>{asset.researchScore ? asset.researchScore.toFixed(0) : 'Insufficient'}</span><span>{asset.outOfSampleMetrics.usableSampleCount}</span><span>{fmt(asset.outOfSampleMetrics.median)}</span><small>{asset.strengths[0] ?? asset.weaknesses[0] ?? 'No usable test sample'}</small></div>)}</div>{study.excludedSymbols.length > 0 && <p className="research-warning">Not ranked: {study.excludedSymbols.join(', ')} did not meet the minimum out-of-sample event rule.</p>}</div> : <p className="universe-empty">Run one identical, causal study across a selected universe. Rankings prioritize out-of-sample evidence and sample confidence—not the largest historical return.</p>}
    {parameterSearch && <div className="parameter-result"><div><strong>Recommended robust region · {parameterSearch.symbol} {parameterSearch.timeframe}</strong><span>{parameterSearch.combinationsTested} combinations · train through {new Date(parameterSearch.split.trainRange.end).toLocaleDateString()}</span></div>{parameterSearch.candidates.slice(0, 3).map((candidate, index) => <div className="parameter-candidate" key={`${index}-${JSON.stringify(candidate.parameters)}`}><b>#{index + 1}</b><code>{Object.entries(candidate.parameters).map(([key, value]) => `${key} ${value}`).join(' · ')}</code><span>OOS {candidate.test.score.toFixed(0)} · robustness {candidate.robustness.toFixed(0)} · {candidate.stability}</span></div>)}<p className="execution-required"><b>Required before comparing strategies:</b> run Trade Simulation with explicit stop, target, maximum holding time, entry rule, and collision policy. These are visible and editable in Trade Study.</p></div>}
    {universalParameterSearch && <div className="parameter-result universal-result"><div><strong>Recommended universal region · {universalParameterSearch.timeframe}</strong><span>{universalParameterSearch.combinationsTested} combinations · common coverage {new Date(universalParameterSearch.commonRange.start).toLocaleDateString()} – {new Date(universalParameterSearch.commonRange.end).toLocaleDateString()}</span></div>{universalParameterSearch.candidates.slice(0, 3).map((candidate, index) => <div className="parameter-candidate" key={`${index}-${JSON.stringify(candidate.parameters)}`}><b>#{index + 1}</b><code>{Object.entries(candidate.parameters).map(([key, value]) => `${key} ${value}`).join(' · ')}</code><span>cross-asset {candidate.crossAssetScore.toFixed(0)} · {candidate.perAsset.filter((item) => !item.rejected).length}/{candidate.perAsset.length} valid OOS samples</span></div>)}<p className="execution-required"><b>Recommended for comparison:</b> use this shared region only after running the same stop, target, maximum-hold, entry, and collision rules in Trade Simulation.</p></div>}
  </section>
}
