export interface DemoPrompt {
  id: 'workspace' | 'research' | 'event-study' | 'collaboration' | 'cross-asset' | 'parameter-search' | 'universe-optimization' | 'universal-settings' | 'trade-simulation' | 'focus-trade'
  label: string
  prompt: string
}

/** Competition-safe prompts only describe workflows; results always come from loaded data. */
export const demoPrompts: DemoPrompt[] = [
  { id: 'workspace', label: '0 · Check workspace', prompt: "Use QuantMCP's WebMCP tools to tell me the current active asset, timeframe, and selected research universe." },
  { id: 'universal-settings', label: '1 · Universal settings', prompt: 'Start the strategy workflow by searching one robust parameter region across the selected universe. Explore feasible Price < SMA, RSI below threshold, and volatility-percentile conditions using chronological out-of-sample validation; do not use the old fixed SMA(200), RSI(14) < 35, volatility > 80 rule.' },
  { id: 'cross-asset', label: '2 · Validate universe', prompt: 'Apply the saved universal parameter region across the selected assets. Rank markets by out-of-sample robustness and identify the best valid asset to take into focused research.' },
  { id: 'parameter-search', label: '3 · Refine best asset', prompt: 'On the top-ranked asset, optionally refine the saved universal region with a bounded asset-specific parameter search. Keep only stable out-of-sample candidates, not the highest in-sample result.' },
  { id: 'research', label: '4 · Research best asset', prompt: 'Use the saved universal or asset-refined robust settings on the selected best asset. Generate the matching historical events in the shared workspace; do not replace the strategy with independent conditions.' },
  { id: 'event-study', label: '5 · Event study', prompt: 'Analyze the 1, 5, 10 and 20 bar forward returns for the events generated by the saved strategy settings.' },
  { id: 'trade-simulation', label: '6 · Trade simulation', prompt: 'Simulate historical long trades from the saved-strategy events using next-bar entry, a 1 ATR stop, a 2R target, a 20-bar maximum hold, and stop-first collision policy. Then identify the strongest and weakest resolved trades.' },
  { id: 'focus-trade', label: '7 · Focus a trade', prompt: 'Focus the chart on the selected historical trade and show its entry, stop, target, risk-reward, and exit outcome.' },
  { id: 'collaboration', label: '8 · Human + agent review', prompt: 'Review one strongest and one weakest historical trade. Focus each case and add concise evidence-based annotations without making a live trading recommendation.' },
  { id: 'universe-optimization', label: 'Optional · Independent comparison', prompt: 'For comparison only, optimize supported parameters independently for every available asset and show how their out-of-sample stability differs from the saved universal region.' },
]

export const recommendedDemoPrompt = demoPrompts[1]
